-- Agent Table
CREATE TABLE IF NOT EXISTS agents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    ip VARCHAR(50) NOT NULL,
    port INT NOT NULL,
    status VARCHAR(50) DEFAULT 'INACTIVE'
);

-- Metric Table
CREATE TABLE IF NOT EXISTS metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL,
    metric_type VARCHAR(255) NOT NULL,
    metric_value DOUBLE NOT NULL,
    timestamp BIGINT NOT NULL
);

-- Alert Rule Table
CREATE TABLE IF NOT EXISTS alert_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    agent_id BIGINT,
    metric_type VARCHAR(255) NOT NULL,
    condition VARCHAR(10) NOT NULL,
    threshold DOUBLE NOT NULL,
    severity VARCHAR(50) NOT NULL,
    enabled BOOLEAN DEFAULT TRUE
);

-- Alert Table (triggered alerts)
CREATE TABLE IF NOT EXISTS alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_rule_id BIGINT NOT NULL,
    agent_id BIGINT NOT NULL,
    rule_name VARCHAR(255) NOT NULL,
    metric_type VARCHAR(255) NOT NULL,
    trigger_value DOUBLE NOT NULL,
    threshold DOUBLE NOT NULL,
    severity VARCHAR(50) NOT NULL,
    status VARCHAR(50) DEFAULT 'ACTIVE',
    first_triggered_at BIGINT NOT NULL,
    last_triggered_at BIGINT NOT NULL,
    trigger_count INT DEFAULT 1,
    acknowledged_by VARCHAR(255),
    acknowledged_at BIGINT,
    resolve_note VARCHAR(1000),
    UNIQUE INDEX unique_alert_rule_agent (alert_rule_id, agent_id)
);

-- Emergency Knowledge Table
CREATE TABLE IF NOT EXISTS emergency_knowledge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_rule_id BIGINT NOT NULL UNIQUE,
    title VARCHAR(500) NOT NULL,
    description VARCHAR(2000),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

-- Emergency Steps Table
CREATE TABLE IF NOT EXISTS emergency_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id BIGINT NOT NULL,
    step_order INT NOT NULL,
    description VARCHAR(1000) NOT NULL,
    linux_command VARCHAR(2000) NOT NULL,
    depends_on BIGINT,
    notes VARCHAR(1000)
);

-- Create Indexes
CREATE INDEX IF NOT EXISTS idx_metrics_agent_id ON metrics(agent_id);
CREATE INDEX IF NOT EXISTS idx_metrics_timestamp ON metrics(timestamp);
CREATE INDEX IF NOT EXISTS idx_alert_rules_enabled ON alert_rules(enabled);
CREATE INDEX IF NOT EXISTS idx_alerts_status ON alerts(status);
CREATE INDEX IF NOT EXISTS idx_alerts_agent_id ON alerts(agent_id);
CREATE INDEX IF NOT EXISTS idx_alerts_last_triggered ON alerts(last_triggered_at);
CREATE INDEX IF NOT EXISTS idx_emergency_knowledge_alert_rule ON emergency_knowledge(alert_rule_id);
CREATE INDEX IF NOT EXISTS idx_emergency_steps_knowledge ON emergency_steps(knowledge_id);
CREATE INDEX IF NOT EXISTS idx_emergency_steps_order ON emergency_steps(step_order);