-- ========================================
-- DDL: Database Schema Definitions
-- ========================================

-- Agent Table
CREATE TABLE IF NOT EXISTS agents (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    ip VARCHAR(50) NOT NULL,
    port INT NOT NULL,
    app_code VARCHAR(10),
    status VARCHAR(20) DEFAULT 'INACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Metric Table
CREATE TABLE IF NOT EXISTS metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id VARCHAR(36) NOT NULL,
    app_code VARCHAR(10),
    metric_type VARCHAR(255) NOT NULL,
    metric_value DOUBLE NOT NULL,
    text_value VARCHAR(1000),
    timestamp TIMESTAMP NOT NULL
);

-- Alert Rule Table
CREATE TABLE IF NOT EXISTS alert_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    agent_id VARCHAR(36),
    metric_type VARCHAR(255) NOT NULL,
    condition VARCHAR(20) NOT NULL,
    threshold DOUBLE,
    threshold_text VARCHAR(500),
    severity VARCHAR(20) NOT NULL,
    alert_message VARCHAR(1000),
    enabled BOOLEAN DEFAULT TRUE
);

-- Alert Table (triggered alerts)
CREATE TABLE IF NOT EXISTS alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_rule_id BIGINT NOT NULL,
    agent_id VARCHAR(36) NOT NULL,
    app_code VARCHAR(10),
    rule_name VARCHAR(255) NOT NULL,
    metric_type VARCHAR(255) NOT NULL,
    trigger_value DOUBLE,
    trigger_value_text VARCHAR(1000),
    threshold DOUBLE,
    threshold_text VARCHAR(500),
    severity VARCHAR(20) NOT NULL,
    alert_message VARCHAR(1000),
    status VARCHAR(20) DEFAULT 'ACTIVE',
    first_triggered_at TIMESTAMP NOT NULL,
    last_triggered_at TIMESTAMP NOT NULL,
    trigger_count INT DEFAULT 1,
    acknowledged_by VARCHAR(255),
    acknowledged_at TIMESTAMP,
    resolve_note VARCHAR(1000),
    resolved_at TIMESTAMP,
    external_alert_id VARCHAR(100)
);

-- Emergency Knowledge Table
CREATE TABLE IF NOT EXISTS emergency_knowledge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    description VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Alert Rule to Emergency Knowledge Association Table (many-to-many)
CREATE TABLE IF NOT EXISTS alert_rule_emergency (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_rule_id BIGINT NOT NULL,
    emergency_knowledge_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    UNIQUE(alert_rule_id, emergency_knowledge_id)
);

-- Emergency Steps Table
CREATE TABLE IF NOT EXISTS emergency_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id BIGINT NOT NULL,
    step_order INT NOT NULL,
    step_type VARCHAR(20) DEFAULT 'COMMAND', -- COMMAND or URL_JUMP
    description VARCHAR(1000) NOT NULL,
    linux_command VARCHAR(2000), -- Used when step_type is COMMAND
    jump_url VARCHAR(1000), -- Used when step_type is URL_JUMP
    agent_id VARCHAR(36),
    depends_on BIGINT,
    notes VARCHAR(1000)
);

-- Metric Definitions Table
CREATE TABLE IF NOT EXISTS metric_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_name VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    metric_type VARCHAR(20) DEFAULT 'NUMERIC',
    collection_command VARCHAR(2000) NOT NULL,
    collection_interval INT DEFAULT 30,
    processing_rule VARCHAR(2000),
    unit VARCHAR(50) DEFAULT '%',
    enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Agent Metric Configuration Table
CREATE TABLE IF NOT EXISTS agent_metric_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id VARCHAR(36) NOT NULL,
    metric_name VARCHAR(255) NOT NULL,
    enabled BOOLEAN DEFAULT TRUE,
    custom_interval INT,
    last_collection_time TIMESTAMP,
    UNIQUE (agent_id, metric_name)
);

-- Alert Channels Table (Third-party alert channels)
CREATE TABLE IF NOT EXISTS alert_channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_code VARCHAR(50) NOT NULL UNIQUE,
    channel_name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    enabled BOOLEAN DEFAULT TRUE,
    created_time TIMESTAMP,
    updated_time TIMESTAMP,
    contact_info VARCHAR(200)
);

-- Third Party Alerts Table (Alerts pushed from external sources)
CREATE TABLE IF NOT EXISTS third_party_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_code VARCHAR(50) NOT NULL,
    external_alert_id VARCHAR(100),
    alert_content TEXT NOT NULL,
    alert_status VARCHAR(20) NOT NULL,
    severity VARCHAR(20),
    push_status VARCHAR(20) NOT NULL,
    failure_reason VARCHAR(500),
    received_time TIMESTAMP NOT NULL,
    processed_time TIMESTAMP,
    source_ip VARCHAR(50),
    app_code VARCHAR(10) NOT NULL
);

-- ========================================
-- Create Indexes
-- ========================================
CREATE INDEX IF NOT EXISTS idx_metrics_agent_id ON metrics(agent_id);
CREATE INDEX IF NOT EXISTS idx_metrics_timestamp ON metrics(timestamp);
CREATE INDEX IF NOT EXISTS idx_alert_rules_enabled ON alert_rules(enabled);
CREATE INDEX IF NOT EXISTS idx_alerts_status ON alerts(status);
CREATE INDEX IF NOT EXISTS idx_alerts_agent_id ON alerts(agent_id);
CREATE INDEX IF NOT EXISTS idx_alerts_last_triggered ON alerts(last_triggered_at);
CREATE INDEX IF NOT EXISTS idx_alerts_external_id ON alerts(external_alert_id);
CREATE INDEX IF NOT EXISTS idx_emergency_steps_knowledge ON emergency_steps(knowledge_id);
CREATE INDEX IF NOT EXISTS idx_emergency_steps_order ON emergency_steps(step_order);
CREATE INDEX IF NOT EXISTS idx_alert_rule_emergency_rule ON alert_rule_emergency(alert_rule_id);
CREATE INDEX IF NOT EXISTS idx_alert_rule_emergency_knowledge ON alert_rule_emergency(emergency_knowledge_id);
CREATE INDEX IF NOT EXISTS idx_metric_definitions_name ON metric_definitions(metric_name);
CREATE INDEX IF NOT EXISTS idx_metric_definitions_enabled ON metric_definitions(enabled);
CREATE INDEX IF NOT EXISTS idx_agent_metric_configs_agent ON agent_metric_configs(agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_metric_configs_metric ON agent_metric_configs(metric_name);
CREATE INDEX IF NOT EXISTS idx_alert_channels_code ON alert_channels(channel_code);
CREATE INDEX IF NOT EXISTS idx_third_party_alerts_channel ON third_party_alerts(channel_code);
CREATE INDEX IF NOT EXISTS idx_third_party_alerts_status ON third_party_alerts(push_status);
CREATE INDEX IF NOT EXISTS idx_third_party_alerts_received ON third_party_alerts(received_time);

-- ========================================
-- Permission Management Tables
-- ========================================

-- System Users Table
CREATE TABLE IF NOT EXISTS sys_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    nickname VARCHAR(100),
    enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- System Roles Table
CREATE TABLE IF NOT EXISTS sys_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(50) NOT NULL UNIQUE,
    role_name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- System Menus Table
CREATE TABLE IF NOT EXISTS sys_menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_code VARCHAR(50) NOT NULL UNIQUE,
    menu_name VARCHAR(100) NOT NULL,
    icon VARCHAR(50),
    sort_order INT DEFAULT 0,
    enabled BOOLEAN DEFAULT TRUE
);

-- User-Role Association Table
CREATE TABLE IF NOT EXISTS sys_user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    UNIQUE(user_id, role_id)
);

-- Role-Menu Association Table
CREATE TABLE IF NOT EXISTS sys_role_menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    UNIQUE(role_id, menu_id)
);

-- Indexes for Permission Tables
CREATE INDEX IF NOT EXISTS idx_sys_users_username ON sys_users(username);
CREATE INDEX IF NOT EXISTS idx_sys_user_roles_user ON sys_user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_sys_user_roles_role ON sys_user_roles(role_id);
CREATE INDEX IF NOT EXISTS idx_sys_role_menus_role ON sys_role_menus(role_id);
CREATE INDEX IF NOT EXISTS idx_sys_role_menus_menu ON sys_role_menus(menu_id);

-- System Applications Table
CREATE TABLE IF NOT EXISTS sys_apps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code VARCHAR(10) NOT NULL UNIQUE,
    app_name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- User-Application Association Table
CREATE TABLE IF NOT EXISTS sys_user_apps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    app_code VARCHAR(10) NOT NULL,
    UNIQUE(user_id, app_code)
);

-- Indexes for Application Tables
CREATE INDEX IF NOT EXISTS idx_sys_apps_code ON sys_apps(app_code);
CREATE INDEX IF NOT EXISTS idx_sys_user_apps_user ON sys_user_apps(user_id);
CREATE INDEX IF NOT EXISTS idx_sys_user_apps_app ON sys_user_apps(app_code);
CREATE INDEX IF NOT EXISTS idx_agents_app_code ON agents(app_code);
CREATE INDEX IF NOT EXISTS idx_metrics_app_code ON metrics(app_code);
CREATE INDEX IF NOT EXISTS idx_alerts_app_code ON alerts(app_code);
CREATE INDEX IF NOT EXISTS idx_third_party_alerts_app_code ON third_party_alerts(app_code);
