-- Agent Table
CREATE TABLE IF NOT EXISTS agents (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    ip VARCHAR(50) NOT NULL,
    port INT NOT NULL,
    status VARCHAR(50) DEFAULT 'INACTIVE'
);

-- Metric Table
CREATE TABLE IF NOT EXISTS metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id VARCHAR(36) NOT NULL,
    metric_type VARCHAR(255) NOT NULL,
    metric_value DOUBLE NOT NULL,
    timestamp BIGINT NOT NULL
);

-- Alert Rule Table
CREATE TABLE IF NOT EXISTS alert_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    agent_id VARCHAR(36),
    metric_type VARCHAR(255) NOT NULL,
    condition VARCHAR(10) NOT NULL,
    threshold DOUBLE NOT NULL,
    severity VARCHAR(50) NOT NULL,
    enabled BOOLEAN DEFAULT TRUE
);

-- Alert Table (triggered alerts)
CREATE TABLE IF NOT EXISTS alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_rule_id BIGINT NOT NULL,
    agent_id VARCHAR(36) NOT NULL,
    rule_name VARCHAR(255) NOT NULL,
    metric_type VARCHAR(255) NOT NULL,
    trigger_value DOUBLE NOT NULL,
    threshold DOUBLE NOT NULL,
    severity VARCHAR(50) NOT NULL,
    status VARCHAR(50) DEFAULT 'ACTIVE',
    first_triggered_at BIGINT NOT NULL,
    last_triggered_at BIGINT NOT NULL,
    trigger_count INT DEFAULT 1,
    acknowledged_by VARCHAR(255),
    acknowledged_at BIGINT,
    resolve_note VARCHAR(1000),
    UNIQUE INDEX unique_alert_rule_agent (alert_rule_id, agent_id)
);

-- Emergency Knowledge Table
CREATE TABLE IF NOT EXISTS emergency_knowledge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_rule_id BIGINT NOT NULL UNIQUE,
    title VARCHAR(500) NOT NULL,
    description VARCHAR(2000),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

-- Emergency Steps Table
CREATE TABLE IF NOT EXISTS emergency_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id BIGINT NOT NULL,
    step_order INT NOT NULL,
    description VARCHAR(1000) NOT NULL,
    linux_command VARCHAR(2000) NOT NULL,
    agent_id VARCHAR(36),
    depends_on BIGINT,
    notes VARCHAR(1000)
);

-- Metric Definitions Table
CREATE TABLE IF NOT EXISTS metric_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_name VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    collection_command VARCHAR(2000) NOT NULL,
    collection_interval INT DEFAULT 30,
    processing_rule VARCHAR(2000),
    unit VARCHAR(50) DEFAULT '%',
    enabled BOOLEAN DEFAULT TRUE,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

-- Agent Metric Configuration Table
CREATE TABLE IF NOT EXISTS agent_metric_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id VARCHAR(36) NOT NULL,
    metric_name VARCHAR(255) NOT NULL,
    enabled BOOLEAN DEFAULT TRUE,
    custom_interval INT,
    last_collection_time BIGINT,
    UNIQUE (agent_id, metric_name)
);

-- Create Indexes
CREATE INDEX IF NOT EXISTS idx_metrics_agent_id ON metrics(agent_id);
CREATE INDEX IF NOT EXISTS idx_metrics_timestamp ON metrics(timestamp);
CREATE INDEX IF NOT EXISTS idx_alert_rules_enabled ON alert_rules(enabled);
CREATE INDEX IF NOT EXISTS idx_alerts_status ON alerts(status);
CREATE INDEX IF NOT EXISTS idx_alerts_agent_id ON alerts(agent_id);
CREATE INDEX IF NOT EXISTS idx_alerts_last_triggered ON alerts(last_triggered_at);
CREATE INDEX IF NOT EXISTS idx_emergency_knowledge_alert_rule ON emergency_knowledge(alert_rule_id);
CREATE INDEX IF NOT EXISTS idx_emergency_steps_knowledge ON emergency_steps(knowledge_id);
CREATE INDEX IF NOT EXISTS idx_emergency_steps_order ON emergency_steps(step_order);
CREATE INDEX IF NOT EXISTS idx_metric_definitions_name ON metric_definitions(metric_name);
CREATE INDEX IF NOT EXISTS idx_metric_definitions_enabled ON metric_definitions(enabled);
CREATE INDEX IF NOT EXISTS idx_agent_metric_configs_agent ON agent_metric_configs(agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_metric_configs_metric ON agent_metric_configs(metric_name);

-- Insert default metric definitions
INSERT INTO metric_definitions (metric_name, display_name, description, collection_command, collection_interval, processing_rule, unit, enabled, created_at, updated_at)
SELECT 'CPU', 'CPU Usage', 'CPU usage percentage', 'top -bn1 | awk ''/Cpu/{print 100-$8}''', 60, NULL, '%', TRUE, CAST(EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) * 1000 AS BIGINT), CAST(EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) * 1000 AS BIGINT)
WHERE NOT EXISTS (SELECT 1 FROM metric_definitions WHERE metric_name = 'CPU');

INSERT INTO metric_definitions (metric_name, display_name, description, collection_command, collection_interval, processing_rule, unit, enabled, created_at, updated_at)
SELECT 'MEMORY', 'Memory Usage', 'Memory usage percentage', 'free | awk ''/Mem/{printf "%.2f", $3/$2*100}''', 60, NULL, '%', TRUE, CAST(EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) * 1000 AS BIGINT), CAST(EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) * 1000 AS BIGINT)
WHERE NOT EXISTS (SELECT 1 FROM metric_definitions WHERE metric_name = 'MEMORY');

INSERT INTO metric_definitions (metric_name, display_name, description, collection_command, collection_interval, processing_rule, unit, enabled, created_at, updated_at)
SELECT 'PORT_8088', 'Port 8088 Status', 'Check if port 8088 is listening', 'netstat -tuln | grep :8088 > /dev/null && echo 1 || echo 0', 30, NULL, '', TRUE, CAST(EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) * 1000 AS BIGINT), CAST(EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) * 1000 AS BIGINT)
WHERE NOT EXISTS (SELECT 1 FROM metric_definitions WHERE metric_name = 'PORT_8088');

-- Insert alert rule for port 8088 monitoring
INSERT INTO alert_rules (name, agent_id, metric_type, condition, threshold, severity, enabled)
SELECT 'Port 8088 Down Alert', NULL, 'PORT_8088', 'LT', 1, 'HIGH', TRUE
WHERE NOT EXISTS (SELECT 1 FROM alert_rules WHERE name = 'Port 8088 Down Alert');